name: stopwatch
description: "Stopwatch app developed with cubit and clean architecture"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  easy_localization: ^3.0.7+1
  auto_route: ^10.0.1
  theme_tailor: ^3.0.2
  theme_tailor_annotation: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
